AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  asset-driver

Parameters:
  S3Region:
    Type: String
    Default: us-east-1
  PrayerListNamesBucket:
    Type: String
  PrayerListLoadedBucket:
    Type: String
  ResidentTableName:
    Type: String
  GeoCodioAPIKey:
    Type: String
  AwsExecutionEnv:
    Type: String
    Default: prod

Globals:
  Function:
    Runtime: ruby2.7
    Timeout: 900
    MemorySize: 512
    Environment:
      Variables:
        S3_REGION:                 !Ref S3Region
        PRAYER_LIST_NAMES_BUCKET:  !Ref PrayerListNamesBucket
        PRAYER_LIST_LOADED_BUCKET: !Ref PrayerListLoadedBucket
        RESIDENT_TABLE_NAME:       !Ref ResidentTableName
        AWS_EXECUTION_ENV:         !Ref AwsExecutionEnv
        GEOCODIO_API_KEY:          !Ref GeoCodioAPIKey


Resources:
  RunRules:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.run_rules
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref PrayerListNamesBucket
        - S3FullAccessPolicy:
            BucketName: !Ref PrayerListLoadedBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ResidentTableName

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref ResidentTableName
      AttributeDefinitions:
        - AttributeName: geohash
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: geohash
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  RunRules:
    Description: "Lambda function for running the prayer list processing rules."
    Value: !GetAtt RunRules.Arn
  S3Region:
    Description: "The AWS region of the output bucket."
    Value: !Sub "${S3Region}"
  PrayerListNamesBucket:
    Description: "Input bucket for prayer list loader files."
    Value: !Sub "${PrayerListNamesBucket}"
  PrayerListLoadedBucket:
    Description: "Output bucket for loaded prayer list loader files."
    Value: !Sub "${PrayerListLoadedBucket}"
  PrayerListResidentTableName:
    Description: "DDB table for Residents."
    Value: !Ref  ResidentTableName
